create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  role text not null default 'customer' check (role in ('customer', 'companion', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists moderation_type text,
  add column if not exists moderation_until timestamptz,
  add column if not exists moderation_note text;

alter table public.profiles
  drop constraint if exists profiles_moderation_type_check;

alter table public.profiles
  add constraint profiles_moderation_type_check
  check (moderation_type is null or moderation_type in ('ban', 'timeout'));

alter table public.profiles enable row level security;

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.user_registrations (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'customer' check (role in ('customer', 'companion', 'admin')),
  registered_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  companion_id uuid references public.profiles(id) on delete set null,
  service_type text not null,
  title text not null,
  details text,
  origin_location text not null,
  destination_location text not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'in_progress', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  updated_at timestamptz not null default now()
);

-- Upgrade an existing service_requests table created by an earlier version.
alter table public.service_requests
  add column if not exists customer_id uuid,
  add column if not exists requester_id uuid,
  add column if not exists companion_id uuid,
  add column if not exists service_type text not null default 'เดินทางทั่วไป',
  add column if not exists title text,
  add column if not exists details text,
  add column if not exists origin_location text not null default 'ไม่ระบุ',
  add column if not exists destination_location text not null default 'ไม่ระบุ',
  add column if not exists status text default 'pending',
  add column if not exists created_at timestamptz default now(),
  add column if not exists accepted_at timestamptz,
  add column if not exists updated_at timestamptz default now();

update public.service_requests
set customer_id = coalesce(customer_id, requester_id),
    requester_id = coalesce(requester_id, customer_id),
  service_type = coalesce(nullif(service_type, ''), 'เดินทางทั่วไป'),
    title = coalesce(nullif(title, ''), 'คำขอใหม่'),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now())
where customer_id is null or requester_id is null or service_type is null or service_type = '' or title is null or title = '' or created_at is null or updated_at is null;

alter table public.service_requests
  alter column customer_id set not null,
  alter column service_type set not null;

create table if not exists public.companion_reviews (
  id bigint generated by default as identity primary key,
  service_request_id uuid not null unique references public.service_requests(id) on delete cascade,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  companion_id uuid not null references public.profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  review text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (length(trim(body)) > 0),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.chat_messages
  add column if not exists read_at timestamptz;

create table if not exists public.moderation_appeals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  admin_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.audit_events enable row level security;
alter table public.user_registrations enable row level security;
alter table public.service_requests enable row level security;
alter table public.moderation_appeals enable row level security;
alter table public.companion_reviews enable row level security;
alter table public.chat_messages enable row level security;

grant select on public.audit_events to authenticated;
grant select on public.user_registrations to authenticated;
grant select, insert, update on public.service_requests to authenticated;
grant select on public.moderation_appeals to authenticated;
grant insert on public.moderation_appeals to authenticated;
grant select, insert on public.companion_reviews to authenticated;
grant select, insert, update on public.chat_messages to authenticated;

create or replace function public.write_audit_event(
  event_name text,
  target_id uuid,
  event_data jsonb default '{}'::jsonb
)
returns void
language sql
security definer set search_path = public
as $$
  insert into public.audit_events (actor_id, target_user_id, event_type, metadata)
  values (auth.uid(), target_id, event_name, event_data);
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url',
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.log_profile_registration()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.user_registrations (user_id, full_name, email, role, registered_at)
  values (new.id, new.full_name, new.email, new.role, new.created_at)
  on conflict (user_id) do update set
    full_name = excluded.full_name,
    email = excluded.email,
    role = excluded.role;
  return new;
end;
$$;

drop trigger if exists on_profile_registered on public.profiles;
create trigger on_profile_registered
  after insert on public.profiles
  for each row execute procedure public.log_profile_registration();

insert into public.user_registrations (user_id, full_name, email, role, registered_at)
select id, full_name, email, role, created_at
from public.profiles
on conflict (user_id) do nothing;

delete from public.audit_events
where event_type = 'user_registered';

insert into public.profiles (id, email, full_name, avatar_url)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'name'),
  raw_user_meta_data ->> 'avatar_url'
from auth.users
on conflict (id) do nothing;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "Users can view related audit events" on public.audit_events;
create policy "Users can view related audit events"
  on public.audit_events for select
  using (actor_id = auth.uid() or target_user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can view user registrations" on public.user_registrations;
create policy "Admins can view user registrations"
  on public.user_registrations for select
  using (public.is_admin());

drop policy if exists "Users can view related service requests" on public.service_requests;
create policy "Users can view related service requests"
  on public.service_requests for select
  using (
    requester_id = auth.uid()
    or companion_id = auth.uid()
    or (companion_id is null and status = 'open')
    or public.is_admin()
  );

drop policy if exists "Customers can create service requests" on public.service_requests;
create policy "Customers can create service requests"
  on public.service_requests for insert
  with check (requester_id = auth.uid());

drop policy if exists "Related users can update service requests" on public.service_requests;
create policy "Related users can update service requests"
  on public.service_requests for update
  using (
    requester_id = auth.uid()
    or companion_id = auth.uid()
    or (companion_id is null and status = 'open')
    or public.is_admin()
  )
  with check (requester_id = auth.uid() or companion_id = auth.uid() or public.is_admin());

drop policy if exists "Users can view related companion reviews" on public.companion_reviews;
create policy "Users can view related companion reviews"
  on public.companion_reviews for select
  using (
    customer_id = auth.uid()
    or companion_id = auth.uid()
    or public.is_admin()
    or exists (
      select 1
      from public.service_requests
      where service_requests.requester_id = auth.uid()
        and service_requests.companion_id = companion_reviews.companion_id
    )
  );

drop policy if exists "Customers can review completed requests" on public.companion_reviews;
create policy "Customers can review completed requests"
  on public.companion_reviews for insert
  with check (
    customer_id = auth.uid()
    and exists (
      select 1
      from public.service_requests
      where service_requests.id = companion_reviews.service_request_id
        and service_requests.requester_id = auth.uid()
        and service_requests.companion_id = companion_reviews.companion_id
        and service_requests.status = 'completed'
    )
  );

drop policy if exists "Users can view their chat messages" on public.chat_messages;
create policy "Users can view their chat messages"
  on public.chat_messages for select
  using (sender_id = auth.uid() or receiver_id = auth.uid() or public.is_admin());

drop policy if exists "Users can send chat messages" on public.chat_messages;
create policy "Users can send chat messages"
  on public.chat_messages for insert
  with check (sender_id = auth.uid() and sender_id <> receiver_id);

drop policy if exists "Recipients can mark chat messages read" on public.chat_messages;
create policy "Recipients can mark chat messages read"
  on public.chat_messages for update
  using (receiver_id = auth.uid())
  with check (receiver_id = auth.uid());

drop policy if exists "Users can view their appeals" on public.moderation_appeals;
create policy "Users can view their appeals"
  on public.moderation_appeals for select
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users can submit their appeals" on public.moderation_appeals;
create policy "Users can submit their appeals"
  on public.moderation_appeals for insert
  with check (user_id = auth.uid());

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles for select
  using (
    id = auth.uid()
    or public.is_admin()
    or exists (
      select 1
      from public.service_requests
      where service_requests.companion_id = profiles.id
        and service_requests.requester_id = auth.uid()
    )
    or exists (
      select 1
      from public.service_requests
      where service_requests.requester_id = profiles.id
        and service_requests.companion_id = auth.uid()
    )
    or exists (
      select 1
      from public.chat_messages
      where (chat_messages.sender_id = auth.uid() and chat_messages.receiver_id = profiles.id)
         or (chat_messages.receiver_id = auth.uid() and chat_messages.sender_id = profiles.id)
    )
  );

grant usage on schema public to authenticated;
grant select, update on public.profiles to authenticated;

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (id = auth.uid())
  with check (id = auth.uid());

create or replace function public.admin_list_profiles()
returns setof public.profiles
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can list profiles';
  end if;

  return query
    select * from public.profiles order by created_at desc;
end;
$$;

revoke all on function public.admin_list_profiles() from public;
grant execute on function public.admin_list_profiles() to authenticated;

create or replace function public.admin_set_user_role(
  target_user_id uuid,
  new_role text
)
returns public.profiles
language plpgsql
security definer set search_path = public
as $$
declare
  changed_profile public.profiles;
  role_value public.user_role;
begin
  if not public.is_admin() then
    raise exception 'Only admins can change roles';
  end if;

  begin
    role_value := new_role::public.user_role;
  exception when invalid_text_representation then
    raise exception 'Invalid role';
  end;

  update public.profiles
  set role = role_value, updated_at = now()
  where id = target_user_id
  returning * into changed_profile;

  if changed_profile.id is null then
    raise exception 'Profile not found';
  end if;

  perform public.write_audit_event(
    'role_changed',
    target_user_id,
    jsonb_build_object('new_role', new_role)
  );

  return changed_profile;
end;
$$;

revoke all on function public.admin_set_user_role(uuid, text) from public;
grant execute on function public.admin_set_user_role(uuid, text) to authenticated;

create or replace function public.admin_set_member_moderation(
  target_user_id uuid,
  action_type text,
  duration_minutes integer,
  moderation_reason text default null
)
returns public.profiles
language plpgsql
security definer set search_path = public
as $$
declare
  changed_profile public.profiles;
begin
  if not public.is_admin() then
    raise exception 'Only admins can moderate members';
  end if;

  if action_type not in ('ban', 'timeout', 'clear') then
    raise exception 'Invalid moderation action';
  end if;

  if action_type <> 'clear' and (duration_minutes is null or duration_minutes < 1) then
    raise exception 'Duration must be at least one minute';
  end if;

  if action_type = 'clear' then
    update public.profiles
    set moderation_type = null,
        moderation_until = null,
        moderation_note = null,
        updated_at = now()
    where id = target_user_id
    returning * into changed_profile;
  else
    update public.profiles
    set moderation_type = action_type,
        moderation_until = now() + make_interval(mins => duration_minutes),
        moderation_note = nullif(trim(moderation_reason), ''),
        updated_at = now()
    where id = target_user_id
    returning * into changed_profile;
  end if;

  if changed_profile.id is null then
    raise exception 'Profile not found';
  end if;

  perform public.write_audit_event(
    case when action_type = 'clear' then 'moderation_cleared' else 'moderation_applied' end,
    target_user_id,
    jsonb_build_object(
      'moderation_type', action_type,
      'duration_minutes', duration_minutes,
      'note', moderation_reason,
      'until', changed_profile.moderation_until
    )
  );

  return changed_profile;
end;
$$;

revoke all on function public.admin_set_member_moderation(uuid, text, integer, text) from public;
grant execute on function public.admin_set_member_moderation(uuid, text, integer, text) to authenticated;

create or replace function public.submit_moderation_appeal(appeal_reason text)
returns public.moderation_appeals
language plpgsql
security definer set search_path = public
as $$
declare
  new_appeal public.moderation_appeals;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in';
  end if;
  if nullif(trim(appeal_reason), '') is null then
    raise exception 'Appeal reason is required';
  end if;

  insert into public.moderation_appeals (user_id, reason)
  values (auth.uid(), trim(appeal_reason))
  returning * into new_appeal;

  perform public.write_audit_event(
    'moderation_appeal_submitted',
    auth.uid(),
    jsonb_build_object('appeal_id', new_appeal.id, 'reason', new_appeal.reason)
  );
  return new_appeal;
end;
$$;

revoke all on function public.submit_moderation_appeal(text) from public;
grant execute on function public.submit_moderation_appeal(text) to authenticated;

create or replace function public.admin_review_moderation_appeal(
  appeal_id bigint,
  decision text,
  review_note text default null
)
returns public.moderation_appeals
language plpgsql
security definer set search_path = public
as $$
declare
  changed_appeal public.moderation_appeals;
begin
  if not public.is_admin() then
    raise exception 'Only admins can review appeals';
  end if;
  if decision not in ('approved', 'rejected') then
    raise exception 'Invalid appeal decision';
  end if;

  update public.moderation_appeals
  set status = decision,
      admin_note = nullif(trim(review_note), ''),
      reviewed_by = auth.uid(),
      reviewed_at = now()
  where id = appeal_id and status = 'pending'
  returning * into changed_appeal;

  if changed_appeal.id is null then
    raise exception 'Pending appeal not found';
  end if;

  if decision = 'approved' then
    update public.profiles
    set moderation_type = null, moderation_until = null, moderation_note = null, updated_at = now()
    where id = changed_appeal.user_id;
  end if;

  perform public.write_audit_event(
    'moderation_appeal_reviewed',
    changed_appeal.user_id,
    jsonb_build_object('appeal_id', appeal_id, 'decision', decision, 'note', review_note)
  );
  return changed_appeal;
end;
$$;

revoke all on function public.admin_review_moderation_appeal(bigint, text, text) from public;
grant execute on function public.admin_review_moderation_appeal(bigint, text, text) to authenticated;

notify pgrst, 'reload schema';

-- Replace this email before running the script for the first time.
update public.profiles
set role = 'admin', updated_at = now()
where email = 'YOUR_GOOGLE_EMAIL@example.com';

-- Verification results
select 'profiles table' as check_name,
       to_regclass('public.profiles') as result;

select 'admin_list_profiles function' as check_name,
       to_regprocedure('public.admin_list_profiles()') as result;

select 'admin_set_user_role function' as check_name,
       to_regprocedure('public.admin_set_user_role(uuid,text)') as result;

select 'admin_set_member_moderation function' as check_name,
       to_regprocedure('public.admin_set_member_moderation(uuid,text,integer,text)') as result;

select 'submit_moderation_appeal function' as check_name,
       to_regprocedure('public.submit_moderation_appeal(text)') as result;

select 'admin_review_moderation_appeal function' as check_name,
       to_regprocedure('public.admin_review_moderation_appeal(bigint,text,text)') as result;

select 'authenticated can call admin_list_profiles' as check_name,
       has_function_privilege(
         'authenticated',
         'public.admin_list_profiles()',
         'EXECUTE'
       ) as result;

select 'authenticated can call admin_set_user_role' as check_name,
       has_function_privilege(
         'authenticated',
         'public.admin_set_user_role(uuid,text)',
         'EXECUTE'
       ) as result;

select id, email, full_name, role, created_at, updated_at
from public.profiles
order by created_at desc;